export const STORAGES = {
    PRODUCTIMAGES: "PRODUCTIMAGES",
    PRODUCTICON: "PRODUCTICON"
};

export const COLLECTIONS = {
    PRODUCTS: "PRODUCTS",
    RATINGS: "RATINGS",
    USERS: "USERS",
    TRANSACTIONS: "TRANSACTIONS",
    RULES: "Rules",
    ORDERS: "Orders",
};
